const DICT_EXCL_KEY = 'EXCLUDED_TERMS';
const ANNOTATION_DENSITY_KEY = 'ANNOTATION_DENSITY';
const AUTORUN_DOMAINS_KEY = 'AUTORUN_DOMAINS';
const SHOW_PHONETIC_KEY = 'SHOW_PHONETIC';

const DEFAULT_ANNOTATION_DENSITY = 50;
const DEFAULT_SHOW_PHONETIC = true;
